feat(msg-parser/huobi): Implemented `parse_candlestick()` for huobi
crypto-crawler/crypto-crawler-rs pull request #54
Opened 2022-09-08 09:19 UTC by iyangdianfeng

Adding Huobi message resolution

2022-09-08 10:42 UTC, soulmachine requested changes
Please merge main branch by running `git checkout binance_parse_candlestick && git merge main`

2022-09-08 10:43 UTC, soulmachine requested changes
`cargo fmt` failed, please run `cargo fmt` locally

2022-09-08 14:11 UTC, pan93412 requested changes

2022-09-08 14:11 UTC, pan93412 commented on crypto-msg-parser/src/exchanges/huobi/huobi_spot.rs
> +    // obj.data.k
Better to remove this dead code.

2022-09-09 08:23 UTC, soulmachine commented on crypto-msg-parser/src/exchanges/huobi/huobi_spot.rs
> +    // obj.data.k
Removed

2022-09-09 08:23 UTC, soulmachine approved these changes

2022-09-09 08:25 UTC, merged