Gate parse candlestick
crypto-crawler/crypto-crawler-rs pull request #55
Opened 2022-09-08 13:59 UTC by iyangdianfeng

Add message parsing of Gate

2022-09-08 14:15 UTC, pan93412 requested changes

2022-09-08 14:15 UTC, pan93412 commented on crypto-msg-parser/src/exchanges/gate/gate_spot_current.rs
> +    // let period = ch[0].to_string();
Better to remove this dead code.

2022-09-08 14:15 UTC, pan93412 commented on crypto-msg-parser/src/exchanges/gate/gate_swap.rs
> +    a: String, //基础货币交易量
Add space between `//` and `基礎`.

2022-09-08 14:15 UTC, pan93412 commented on crypto-msg-parser/src/exchanges/gate/gate_swap.rs
> +        // let period = ch[0].to_string();
Better to remove this dead code.

2022-09-08 14:15 UTC, pan93412 commented
Besides, you can run `cargo fmt` to format your code.

2022-09-09 08:26 UTC, pan93412 approved these changes

2022-09-09 09:58 UTC, soulmachine requested changes
@iyangdianfeng don't use Chinese in comment, using English is a good habit, which can bring your project to wider audience over the world

2022-09-10 10:41 UTC, soulmachine approved these changes

2022-09-10 10:41 UTC, merged